version: '3.0'
services:
  pg_twitter_bot: #pg_botname_with_underline_bot
    image: postgres:9.5
    container_name: pg_twitter_bot # same as service name
    restart: always 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=twitter
      - TZ=Asia/Tehran
    volumes:
      - /home/barkhordar/docker/volumes/pg_twitter_bot/postgres/:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  twitter_bot: # botname_bot
    image: twitter_bot:0.0.1
    container_name: twitter_bot #same as service name
    environment:
    #   PostgreSQL Config
      - POSTGRES_USER=postgres  #env name like postgres env's
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=twitter
      - POSTGRES_HOST=pg_twitter_bot
      - POSTGRES_PORT=5432
    #   Config
      - BASE_URL=wss://api.bale.ai/v1/bots/
      - TOKEN=649bf46416fa39f1e4893b4fa53faf59c309b54e
      - APP_KEY=vNo9Sp0r1YuQM3jAHjL3C2qvR
      - APP_SECRET=o0eLxGxMBT78KOrOmFbq5HrhgGQ15ge7Ae5geNWdowWVTZSKjI
      - TWEET_COUNT=3
      - TIME_SLEEP=
    depends_on:
     - pg_twitter_bot
    restart: always # use always